on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - uses: actions/upload-artifact@v4
        name: Upload artifacts
        with:
          name: application-binaries  
          path: .      

  unit-ui-tests:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download application artifacts
        uses: actions/download-artifact@v4
        with:
          name: application-binaries
      - name: Run UI unit tests
        run: dotnet test tests/GameSync.ViewModels.Unit.Tests/GameSync.ViewModels.Unit.Tests.csproj --configuration Release --no-build

  unit-model-tests:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download application artifacts
        uses: actions/download-artifact@v4
        with:
          name: application-binaries
      - name: Run model unit tests
        run: dotnet test tests/GameSync.Models.Unit.Tests/GameSync.Models.Unit.Tests.csproj --configuration Release --no-build